---
title: "Getting Started"
author: "Joshua C. Fjelstul, Ph.D."
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

You can use the `euip` package to easily access data from the European Union Infringement Procedure (EUIP) Database, which is part of the European Union Compliance Project (EUCP).

## The EU Infringement Procedure

Infringement cases are legal cases that the Commission launches against EU member states for violations of EU law. Each case is managed by a specific DG and the commissioner of that DG makes the final decisions about how to handle each case in their policy area. The EU's formal infringement procedure infringement procedure is a multi-stage legal process. The Commission opens an infringement cases by sending a member state a letter of formal notice under Article 258 of the Treaty on the Functioning of the European Union (TFEU) informing the member state of an alleged infringement The member state then has an opportunity to respond, either by coming into compliance or by explaining to the Commission why it has not committed an infringement. If the Commission is satisfied with the member state's response — if it is convinced that the member state has corrected the infringement or the member or the member state convinces the Commission that it did not commit an infringement — then the Commission can close the case.

If the Commission is not satisfied, it can proceed to the second stage of the procedure by sending a reasoned opinion. Reasoned opinions present a formal legal argument as to why the member state has committed an infringement. Again, the member state has an opportunity to respond. If the Commission is still not satisfied with the member state's response, it can proceed to the third stage of the procedure by referring the case to the Court of Justice of the European Union (CJEU), which will then issue a binding judgment in the case.

If the member state does not come into compliance after the CJEU has issued a ruling, the Commission can go through the entire process again under Article 260 TFEU. This time, the Commission can ask the CJEU to impose lump sum or per diem fines on the member state to incentivize it to come into compliance. 

Altogether, then, there are 6 stage in the infringement procedure: a letter of formal notice (Article 258), a reasoned opinion (Article 258), a referral to the Court (Article 260), a second letter of formal notice (Article 260), a second reasoned opinion (Article 260), and a second referral to the Court (Article 260). The Commission can close or withdraw a case at any time during the process for any reason. It has complete discretion over whether to prosecute an alleged infringement. 

There are two basic types of infringement cases: noncommunication cases and nonconformity cases. When the EU passes a directive (the main form of EU legislation), individual EU member states are responsible to implement the directive by "transposing" it into national law. EU directives specify policy objectives that member states have to achieve, but member states have flexibility in terms of how to achive those objectives. To implement a directive, member states have to pass national laws that accomplish the objectives set out in the directive by a certain date. These national laws are called national implementation measures (NIMs). 

Noncommunication cases are those in which a member state has failed to communicate to the Commission the NIM(s) it has enacted to transpose a directive by the date specified in the directive. The Commission opens these cases automatically. Nonconformity cases are those in which a member state has enacted NIMs to transpose a directive, but it has implemented the directive incorrectly. The Commission identifies instances of nonconformity through its own investigations and through complaints filed by members of the public.
