################################################################################
# Joshua C. Fjelstul, Ph.D.
# euip R package
# automatically generated by the codebookr R package
################################################################################

#' CSTS data on cases (by department)
#'
#' This dataset includes aggregated data on the number of infringement cases
#' per department per year (cross-sectional time-series data). There is one
#' observation per department per year (2002-2020). The dataset uses current
#' department names.
#'
#' @format A data frame with 6 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{Numeric. The year the case was opened by the Commission.}
#' \item{department_id}{Numeric. An ID number that uniquely identifies each
#' Commission department.}
#' \item{department}{String. The name of the Commission department that opened
#' the infringement case.}
#' \item{department_code}{String. A multi-letter code assigned by the
#' Commission that uniquely identifies each department.}
#' \item{count_cases}{Numeric. A count of the number of cases opened by the
#' Commission at this level of aggregation.}
#' }
"cases_csts_dp"

################################################################################
# end R script
################################################################################
