################################################################################
# Joshua C. Fjelstul, Ph.D.
# euip R package
# automatically generated by the codebookr R package
################################################################################

#' Network data on decisions
#'
#' This dataset includes multi-dimensional network data for infringement
#' decisions. There is one dimension per decision stage. Network data is
#' similar to directed dyad-year data except that it only includes directed
#' dyad-years with at least one decision with respect to each stage. For every
#' year, there is one node per department and one node per member state. Edges
#' can only exist between a department and a member state. There is an edge
#' between a department and a member state with respect to each stage if and
#' only if the department issued at least one decision against the member
#' state during that year. The weight of the edge is the number of decisions
#' that the department opened against the member state. There is one
#' observation per department per member state per year per decision stage
#' (2002-2020), excluding directed dyad-years where the state was not a member
#' of the EU, but only if count of decisions is positive.
#'
#' @format A data frame with 9 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{time}{Numeric. The time period, where \code{2002} is coded \code{1}.
#' }
#' \item{layer_id}{Numeric. An ID number that uniquely identifies each layer
#' of the network.}
#' \item{layer}{String. The layer of the network, which is the decision
#' stage.}
#' \item{from_node_id}{Numeric. An ID number that uniquely identifies each
#' node in the network that creates a link, which is always a Commission
#' department.}
#' \item{from_node}{String. The name of the Commission department that opened
#' the infringement case.}
#' \item{to_node_id}{Numeric. An ID number that uniquely identifies each node
#' in the network that receives a link, which is always a member state.}
#' \item{to_node}{String. The name of the member state that the Commission
#' issued the decision against. }
#' \item{edge_weight}{Numeric. The weight of the edge, which is the number of
#' decisions opened by the Commission.}
#' }
"decisions_net"

################################################################################
# end R script
################################################################################
